
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanckWS", targetNamespace = "http://ws.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanckWS {


    /**
     * 
     * @param montant
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Convert")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Convert", targetNamespace = "http://ws.example.org/", className = "proxy.Convert")
    @ResponseWrapper(localName = "ConvertResponse", targetNamespace = "http://ws.example.org/", className = "proxy.ConvertResponse")
    @Action(input = "http://ws.example.org/BanckWS/ConvertRequest", output = "http://ws.example.org/BanckWS/ConvertResponse")
    public Double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compt
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompt", targetNamespace = "http://ws.example.org/", className = "proxy.GetCompt")
    @ResponseWrapper(localName = "getComptResponse", targetNamespace = "http://ws.example.org/", className = "proxy.GetComptResponse")
    @Action(input = "http://ws.example.org/BanckWS/getComptRequest", output = "http://ws.example.org/BanckWS/getComptResponse")
    public Compt getCompt(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compt>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listComptes", targetNamespace = "http://ws.example.org/", className = "proxy.ListComptes")
    @ResponseWrapper(localName = "listComptesResponse", targetNamespace = "http://ws.example.org/", className = "proxy.ListComptesResponse")
    @Action(input = "http://ws.example.org/BanckWS/listComptesRequest", output = "http://ws.example.org/BanckWS/listComptesResponse")
    public List<Compt> listComptes();

}
