
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanckSW", targetNamespace = "http://ws.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanckSW {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionEuroToDh", targetNamespace = "http://ws.example.org/", className = "proxy.ConversionEuroToDh")
    @ResponseWrapper(localName = "conversionEuroToDhResponse", targetNamespace = "http://ws.example.org/", className = "proxy.ConversionEuroToDhResponse")
    @Action(input = "http://ws.example.org/BanckSW/conversionEuroToDhRequest", output = "http://ws.example.org/BanckSW/conversionEuroToDhResponse")
    public double conversionEuroToDh(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compt>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompts", targetNamespace = "http://ws.example.org/", className = "proxy.GetCompts")
    @ResponseWrapper(localName = "getComptsResponse", targetNamespace = "http://ws.example.org/", className = "proxy.GetComptsResponse")
    @Action(input = "http://ws.example.org/BanckSW/getComptsRequest", output = "http://ws.example.org/BanckSW/getComptsResponse")
    public List<Compt> getCompts();

    /**
     * 
     * @param arg0
     * @return
     *     returns proxy.Compt
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompt", targetNamespace = "http://ws.example.org/", className = "proxy.GetCompt")
    @ResponseWrapper(localName = "getComptResponse", targetNamespace = "http://ws.example.org/", className = "proxy.GetComptResponse")
    @Action(input = "http://ws.example.org/BanckSW/getComptRequest", output = "http://ws.example.org/BanckSW/getComptResponse")
    public Compt getCompt(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
